package gui;

import core.BinPackProduct;
import core.HidatoSolver;
import javax.swing.DefaultListModel;
import org.jacop.core.IntVar;

/**
 * Class is created in order to show results at Graphical User Interface. Most
 * of the parts are created autmatically by NetBEANS.
 *
 * @author Hüsnü ISLEYEN
 * @version 1.0
 */
public class AppFrame extends javax.swing.JFrame {

    /**
     * Creates new form AppFrame
     */
    public AppFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        C56 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        C55 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        C53 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        C57 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        C54 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        C52 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        C51 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        C50 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        C40 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        C41 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        C42 = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        C43 = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        C44 = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        C45 = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        C46 = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        C47 = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        C30 = new javax.swing.JTextPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        C31 = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        C32 = new javax.swing.JTextPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        C33 = new javax.swing.JTextPane();
        jScrollPane22 = new javax.swing.JScrollPane();
        C34 = new javax.swing.JTextPane();
        jScrollPane23 = new javax.swing.JScrollPane();
        C35 = new javax.swing.JTextPane();
        jScrollPane24 = new javax.swing.JScrollPane();
        C36 = new javax.swing.JTextPane();
        jScrollPane25 = new javax.swing.JScrollPane();
        C37 = new javax.swing.JTextPane();
        jScrollPane26 = new javax.swing.JScrollPane();
        C20 = new javax.swing.JTextPane();
        jScrollPane27 = new javax.swing.JScrollPane();
        C21 = new javax.swing.JTextPane();
        jScrollPane28 = new javax.swing.JScrollPane();
        C22 = new javax.swing.JTextPane();
        jScrollPane29 = new javax.swing.JScrollPane();
        C23 = new javax.swing.JTextPane();
        jScrollPane30 = new javax.swing.JScrollPane();
        C24 = new javax.swing.JTextPane();
        jScrollPane31 = new javax.swing.JScrollPane();
        C25 = new javax.swing.JTextPane();
        jScrollPane32 = new javax.swing.JScrollPane();
        C26 = new javax.swing.JTextPane();
        jScrollPane33 = new javax.swing.JScrollPane();
        C27 = new javax.swing.JTextPane();
        jScrollPane34 = new javax.swing.JScrollPane();
        C10 = new javax.swing.JTextPane();
        jScrollPane35 = new javax.swing.JScrollPane();
        C11 = new javax.swing.JTextPane();
        jScrollPane36 = new javax.swing.JScrollPane();
        C12 = new javax.swing.JTextPane();
        jScrollPane37 = new javax.swing.JScrollPane();
        C13 = new javax.swing.JTextPane();
        jScrollPane38 = new javax.swing.JScrollPane();
        C14 = new javax.swing.JTextPane();
        jScrollPane39 = new javax.swing.JScrollPane();
        C15 = new javax.swing.JTextPane();
        jScrollPane40 = new javax.swing.JScrollPane();
        C16 = new javax.swing.JTextPane();
        jScrollPane41 = new javax.swing.JScrollPane();
        C17 = new javax.swing.JTextPane();
        jScrollPane42 = new javax.swing.JScrollPane();
        C00 = new javax.swing.JTextPane();
        jScrollPane43 = new javax.swing.JScrollPane();
        C01 = new javax.swing.JTextPane();
        jScrollPane44 = new javax.swing.JScrollPane();
        C02 = new javax.swing.JTextPane();
        jScrollPane45 = new javax.swing.JScrollPane();
        C03 = new javax.swing.JTextPane();
        jScrollPane46 = new javax.swing.JScrollPane();
        C04 = new javax.swing.JTextPane();
        jScrollPane47 = new javax.swing.JScrollPane();
        C05 = new javax.swing.JTextPane();
        jScrollPane48 = new javax.swing.JScrollPane();
        C06 = new javax.swing.JTextPane();
        jScrollPane49 = new javax.swing.JScrollPane();
        C07 = new javax.swing.JTextPane();
        jScrollPane51 = new javax.swing.JScrollPane();
        C61 = new javax.swing.JTextPane();
        jScrollPane52 = new javax.swing.JScrollPane();
        C62 = new javax.swing.JTextPane();
        jScrollPane53 = new javax.swing.JScrollPane();
        C63 = new javax.swing.JTextPane();
        jScrollPane54 = new javax.swing.JScrollPane();
        C64 = new javax.swing.JTextPane();
        jScrollPane55 = new javax.swing.JScrollPane();
        C65 = new javax.swing.JTextPane();
        jScrollPane56 = new javax.swing.JScrollPane();
        C66 = new javax.swing.JTextPane();
        jScrollPane57 = new javax.swing.JScrollPane();
        C67 = new javax.swing.JTextPane();
        jScrollPane58 = new javax.swing.JScrollPane();
        C70 = new javax.swing.JTextPane();
        jScrollPane59 = new javax.swing.JScrollPane();
        C71 = new javax.swing.JTextPane();
        jScrollPane60 = new javax.swing.JScrollPane();
        C72 = new javax.swing.JTextPane();
        jScrollPane61 = new javax.swing.JScrollPane();
        C73 = new javax.swing.JTextPane();
        jScrollPane62 = new javax.swing.JScrollPane();
        C74 = new javax.swing.JTextPane();
        jScrollPane63 = new javax.swing.JScrollPane();
        C75 = new javax.swing.JTextPane();
        jScrollPane64 = new javax.swing.JScrollPane();
        C76 = new javax.swing.JTextPane();
        jScrollPane65 = new javax.swing.JScrollPane();
        C77 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane66 = new javax.swing.JScrollPane();
        C60 = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        loadButton = new javax.swing.JButton();
        jScrollPane50 = new javax.swing.JScrollPane();
        truckList = new javax.swing.JList();
        jScrollPane67 = new javax.swing.JScrollPane();
        planText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("INFORMATION ABOUT PROBLEMS\n\n1- Hidato Puzzle\n\nIt is a kind of logic puzzle game and also known as “Hidoku”. The goal of Hidato is to fill the grid with consecutive numbers that connect horizontally, \nvertically, or diagonally. Each cell value should have proper value near of it - \nExample:  \n\t|a|b|c|  one of the letters should be 4 and one of the letters should be 6\n\t|d|5|e| \n\t|f|g|h|\nExample problem is taken from Wikipedia. According to given numbers, grid is created in Q1 - Hidato Puzzle Tab.\n\n2- Binpacking & Product Scheduling/Planning\n\nWe have some resources which have different and undivisible sizes. First these resources should loaded\ntrucks(Binpacking), and then Product planning should be created for Max Income.\n\nExample: \n\nResources --> R1:{10,10,10,10}       R2:{5,5,5,5}       R3:{2,2,2,2}\n\nTrucks: 10 Trucks which has 10 Capacity\n              5  Trucks which has 15 Capacity\n\n Products --> P1:{10x1, 2x1} P2:{5x2,2x2} P3:{2x1}\n\nIncome --> P1 = 15 PLN, P2=8 PLN, P3=5 PLN\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Info", jPanel2);

        C56.setEditable(false);
        C56.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C56.setText("0");
        C56.setAutoscrolls(false);
        jScrollPane2.setViewportView(C56);

        C55.setEditable(false);
        C55.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C55.setText("0");
        C55.setAutoscrolls(false);
        jScrollPane5.setViewportView(C55);

        C53.setEditable(false);
        C53.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C53.setText("0");
        C53.setAutoscrolls(false);
        jScrollPane3.setViewportView(C53);

        C57.setEditable(false);
        C57.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C57.setAutoscrolls(false);
        C57.setPreferredSize(null);
        jScrollPane4.setViewportView(C57);

        C54.setEditable(false);
        C54.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C54.setText("18");
        C54.setAutoscrolls(false);
        jScrollPane6.setViewportView(C54);

        C52.setEditable(false);
        C52.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C52.setText("0");
        C52.setAutoscrolls(false);
        jScrollPane7.setViewportView(C52);

        C51.setEditable(false);
        C51.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C51.setAutoscrolls(false);
        jScrollPane8.setViewportView(C51);

        C50.setEditable(false);
        C50.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C50.setAutoscrolls(false);
        jScrollPane9.setViewportView(C50);

        C40.setEditable(false);
        C40.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C40.setText("27");
        C40.setAutoscrolls(false);
        jScrollPane10.setViewportView(C40);

        C41.setEditable(false);
        C41.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C41.setText("0");
        C41.setAutoscrolls(false);
        jScrollPane11.setViewportView(C41);

        C42.setEditable(false);
        C42.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C42.setText("0");
        C42.setAutoscrolls(false);
        jScrollPane12.setViewportView(C42);

        C43.setEditable(false);
        C43.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C43.setText("0");
        C43.setAutoscrolls(false);
        jScrollPane13.setViewportView(C43);

        C44.setEditable(false);
        C44.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C44.setText("9");
        C44.setAutoscrolls(false);
        jScrollPane14.setViewportView(C44);

        C45.setEditable(false);
        C45.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C45.setText("0");
        C45.setAutoscrolls(false);
        jScrollPane15.setViewportView(C45);

        C46.setEditable(false);
        C46.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C46.setForeground(new java.awt.Color(204, 0, 0));
        C46.setText("1");
        C46.setAutoscrolls(false);
        C46.setCaretColor(new java.awt.Color(255, 102, 0));
        jScrollPane16.setViewportView(C46);

        C47.setEditable(false);
        C47.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C47.setAutoscrolls(false);
        C47.setPreferredSize(null);
        jScrollPane17.setViewportView(C47);

        C30.setEditable(false);
        C30.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C30.setText("0");
        C30.setAutoscrolls(false);
        jScrollPane18.setViewportView(C30);

        C31.setEditable(false);
        C31.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C31.setText("26");
        C31.setAutoscrolls(false);
        jScrollPane19.setViewportView(C31);

        C32.setEditable(false);
        C32.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C32.setText("0");
        C32.setAutoscrolls(false);
        jScrollPane20.setViewportView(C32);

        C33.setEditable(false);
        C33.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C33.setText("13");
        C33.setAutoscrolls(false);
        jScrollPane21.setViewportView(C33);

        C34.setEditable(false);
        C34.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C34.setForeground(new java.awt.Color(204, 0, 0));
        C34.setText("40");
        C34.setAutoscrolls(false);
        C34.setCaretColor(new java.awt.Color(255, 102, 0));
        jScrollPane22.setViewportView(C34);

        C35.setEditable(false);
        C35.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C35.setText("11");
        C35.setAutoscrolls(false);
        jScrollPane23.setViewportView(C35);

        C36.setEditable(false);
        C36.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C36.setAutoscrolls(false);
        jScrollPane24.setViewportView(C36);

        C37.setEditable(false);
        C37.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C37.setAutoscrolls(false);
        C37.setPreferredSize(null);
        jScrollPane25.setViewportView(C37);

        C20.setEditable(false);
        C20.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C20.setText("0");
        C20.setAutoscrolls(false);
        jScrollPane26.setViewportView(C20);

        C21.setEditable(false);
        C21.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C21.setText("0");
        C21.setAutoscrolls(false);
        jScrollPane27.setViewportView(C21);

        C22.setEditable(false);
        C22.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C22.setText("0");
        C22.setAutoscrolls(false);
        jScrollPane28.setViewportView(C22);

        C23.setEditable(false);
        C23.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C23.setText("21");
        C23.setAutoscrolls(false);
        jScrollPane29.setViewportView(C23);

        C24.setEditable(false);
        C24.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C24.setText("0");
        C24.setAutoscrolls(false);
        jScrollPane30.setViewportView(C24);

        C25.setEditable(false);
        C25.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C25.setText("0");
        C25.setAutoscrolls(false);
        jScrollPane31.setViewportView(C25);

        C26.setEditable(false);
        C26.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C26.setAutoscrolls(false);
        jScrollPane32.setViewportView(C26);

        C27.setEditable(false);
        C27.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C27.setAutoscrolls(false);
        C27.setPreferredSize(null);
        jScrollPane33.setViewportView(C27);

        C10.setEditable(false);
        C10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C10.setText("0");
        C10.setAutoscrolls(false);
        jScrollPane34.setViewportView(C10);

        C11.setEditable(false);
        C11.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C11.setText("0");
        C11.setAutoscrolls(false);
        jScrollPane35.setViewportView(C11);

        C12.setEditable(false);
        C12.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C12.setText("24");
        C12.setAutoscrolls(false);
        jScrollPane36.setViewportView(C12);

        C13.setEditable(false);
        C13.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C13.setText("22");
        C13.setAutoscrolls(false);
        jScrollPane37.setViewportView(C13);

        C14.setEditable(false);
        C14.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C14.setText("0");
        C14.setAutoscrolls(false);
        jScrollPane38.setViewportView(C14);

        C15.setEditable(false);
        C15.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C15.setAutoscrolls(false);
        jScrollPane39.setViewportView(C15);

        C16.setEditable(false);
        C16.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C16.setAutoscrolls(false);
        jScrollPane40.setViewportView(C16);

        C17.setEditable(false);
        C17.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C17.setAutoscrolls(false);
        C17.setPreferredSize(null);
        jScrollPane41.setViewportView(C17);

        C00.setEditable(false);
        C00.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C00.setText("0");
        C00.setAutoscrolls(false);
        jScrollPane42.setViewportView(C00);

        C01.setEditable(false);
        C01.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C01.setText("33");
        C01.setAutoscrolls(false);
        jScrollPane43.setViewportView(C01);

        C02.setEditable(false);
        C02.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C02.setText("35");
        C02.setAutoscrolls(false);
        jScrollPane44.setViewportView(C02);

        C03.setEditable(false);
        C03.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C03.setText("0");
        C03.setAutoscrolls(false);
        jScrollPane45.setViewportView(C03);

        C04.setEditable(false);
        C04.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C04.setText("0");
        C04.setAutoscrolls(false);
        jScrollPane46.setViewportView(C04);

        C05.setEditable(false);
        C05.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C05.setAutoscrolls(false);
        jScrollPane47.setViewportView(C05);

        C06.setEditable(false);
        C06.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C06.setAutoscrolls(false);
        jScrollPane48.setViewportView(C06);

        C07.setEditable(false);
        C07.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C07.setAutoscrolls(false);
        C07.setPreferredSize(null);
        jScrollPane49.setViewportView(C07);

        C61.setEditable(false);
        C61.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C61.setAutoscrolls(false);
        jScrollPane51.setViewportView(C61);

        C62.setEditable(false);
        C62.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C62.setAutoscrolls(false);
        jScrollPane52.setViewportView(C62);

        C63.setEditable(false);
        C63.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C63.setAutoscrolls(false);
        jScrollPane53.setViewportView(C63);

        C64.setEditable(false);
        C64.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C64.setText("0");
        C64.setAutoscrolls(false);
        jScrollPane54.setViewportView(C64);

        C65.setEditable(false);
        C65.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C65.setText("7");
        C65.setAutoscrolls(false);
        jScrollPane55.setViewportView(C65);

        C66.setEditable(false);
        C66.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C66.setText("0");
        C66.setAutoscrolls(false);
        jScrollPane56.setViewportView(C66);

        C67.setEditable(false);
        C67.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C67.setText("0");
        C67.setAutoscrolls(false);
        C67.setPreferredSize(null);
        jScrollPane57.setViewportView(C67);

        C70.setEditable(false);
        C70.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C70.setAutoscrolls(false);
        jScrollPane58.setViewportView(C70);

        C71.setEditable(false);
        C71.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C71.setAutoscrolls(false);
        jScrollPane59.setViewportView(C71);

        C72.setEditable(false);
        C72.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C72.setAutoscrolls(false);
        jScrollPane60.setViewportView(C72);

        C73.setEditable(false);
        C73.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C73.setAutoscrolls(false);
        jScrollPane61.setViewportView(C73);

        C74.setEditable(false);
        C74.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C74.setAutoscrolls(false);
        jScrollPane62.setViewportView(C74);

        C75.setEditable(false);
        C75.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C75.setAutoscrolls(false);
        jScrollPane63.setViewportView(C75);

        C76.setEditable(false);
        C76.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C76.setText("5");
        C76.setAutoscrolls(false);
        jScrollPane64.setViewportView(C76);

        C77.setEditable(false);
        C77.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C77.setText("0");
        C77.setAutoscrolls(false);
        C77.setName(""); // NOI18N
        C77.setPreferredSize(null);
        jScrollPane65.setViewportView(C77);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButton1.setText("Find Solution");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setText("Initial Value(min) = 1 ------------------------- End Value(max) = 40");

        C60.setEditable(false);
        C60.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        C60.setAutoscrolls(false);
        jScrollPane66.setViewportView(C60);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane58, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane59, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane60, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane61, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane62, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane63, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane64, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane65))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jScrollPane66, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane51, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane52, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane53, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane54, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane55, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane56, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane57, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane43, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane44, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane45, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane46, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane48, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane49, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane43, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane44, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane49, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane45, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane46, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane48, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane51, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane52, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane57, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane53, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane54, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane55, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane56, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane66))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane58, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jScrollPane59, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jScrollPane60, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jScrollPane61, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jScrollPane62, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jScrollPane63, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jScrollPane64, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jScrollPane65))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Q1- Hidato Puzzle", jPanel3);

        jTextField1.setEditable(false);
        jTextField1.setText("  RESOURCE - 1 ");

        jTextField2.setEditable(false);
        jTextField2.setText("{10,10,10,10}");

        jTextField3.setEditable(false);
        jTextField3.setText("  RESOURCE - 2 ");

        jTextField4.setEditable(false);
        jTextField4.setText("{5,5,5,5}");

        jTextField5.setEditable(false);
        jTextField5.setText("  RESOURCE - 3 ");

        jTextField6.setEditable(false);
        jTextField6.setText("{2,2,2,2}");

        jTextField7.setEditable(false);
        jTextField7.setText("10 Trucks - Capacity:10");

        jTextField8.setEditable(false);
        jTextField8.setText("5 Trucks - Capacity:15");

        jTextField9.setEditable(false);
        jTextField9.setText("  PRODUCT - 1 ");

        jTextField10.setEditable(false);
        jTextField10.setText("  PRODUCT - 2 ");

        jTextField11.setEditable(false);
        jTextField11.setText("  PRODUCT - 3 ");

        jTextField12.setEditable(false);
        jTextField12.setText("{10x1 + 2x1}");

        jTextField13.setEditable(false);
        jTextField13.setText("{5x2 + 2x2}");

        jTextField14.setEditable(false);
        jTextField14.setText("{2x1}");

        jTextField15.setEditable(false);
        jTextField15.setText("15 PLN");

        jTextField16.setEditable(false);
        jTextField16.setText("8 PLN");

        jTextField17.setEditable(false);
        jTextField17.setText("3 PLN");

        loadButton.setText("Find Solution");
        loadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadButtonMouseClicked(evt);
            }
        });

        jScrollPane50.setViewportView(truckList);

        planText.setColumns(20);
        planText.setRows(5);
        jScrollPane67.setViewportView(planText);

        jLabel2.setText("Trucks Load");

        jLabel3.setText("Product Scheduling/Planning");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane50, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(jTextField10)
                                    .addComponent(jTextField9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField16))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane67, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel2))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane50, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane67, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Q2- Binpacking&Scheduling/Planning", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadButtonMouseClicked

        BinPackProduct solver = new BinPackProduct();
        solver.model();
        solver.search();

        DefaultListModel dlm = new DefaultListModel();
        for (int i = 0; i < solver.trucks.length; i++) {
            dlm.addElement(solver.trucks[i].toString());
        }
        truckList.setModel(dlm);
        solver.resourceAllocation();
        solver.searchMaxIncome();
        planText.setText(solver.text);
    }//GEN-LAST:event_loadButtonMouseClicked

    /**
     * Hidato Solve Button
     *
     * @param evt
     */
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        HidatoSolver a = new HidatoSolver();
        a.model();
        a.search();
        C00.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[0].value()));
        C01.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[1].value()));
        C02.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[2].value()));
        C03.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[3].value()));
        C04.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[4].value()));
        C10.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[5].value()));
        C11.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[6].value()));
        C12.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[7].value()));
        C13.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[8].value()));
        C14.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[9].value()));
        C20.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[10].value()));
        C21.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[11].value()));
        C22.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[12].value()));
        C23.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[13].value()));
        C24.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[14].value()));
        C25.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[15].value()));
        C30.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[16].value()));
        C31.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[17].value()));
        C32.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[18].value()));
        C33.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[19].value()));
        C34.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[20].value()));
        C35.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[21].value()));
        C40.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[22].value()));
        C41.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[23].value()));
        C42.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[24].value()));
        C43.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[25].value()));
        C44.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[26].value()));
        C45.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[27].value()));
        C46.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[28].value()));
        C52.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[29].value()));
        C53.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[30].value()));
        C54.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[31].value()));
        C55.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[32].value()));
        C56.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[33].value()));
        C64.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[34].value()));
        C65.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[35].value()));
        C66.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[36].value()));
        C67.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[37].value()));
        C76.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[38].value()));
        C77.setText(String.valueOf(a.ourTable.toArray(new IntVar[1])[39].value()));

    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane C00;
    private javax.swing.JTextPane C01;
    private javax.swing.JTextPane C02;
    private javax.swing.JTextPane C03;
    private javax.swing.JTextPane C04;
    private javax.swing.JTextPane C05;
    private javax.swing.JTextPane C06;
    private javax.swing.JTextPane C07;
    private javax.swing.JTextPane C10;
    private javax.swing.JTextPane C11;
    private javax.swing.JTextPane C12;
    private javax.swing.JTextPane C13;
    private javax.swing.JTextPane C14;
    private javax.swing.JTextPane C15;
    private javax.swing.JTextPane C16;
    private javax.swing.JTextPane C17;
    private javax.swing.JTextPane C20;
    private javax.swing.JTextPane C21;
    private javax.swing.JTextPane C22;
    private javax.swing.JTextPane C23;
    private javax.swing.JTextPane C24;
    private javax.swing.JTextPane C25;
    private javax.swing.JTextPane C26;
    private javax.swing.JTextPane C27;
    private javax.swing.JTextPane C30;
    private javax.swing.JTextPane C31;
    private javax.swing.JTextPane C32;
    private javax.swing.JTextPane C33;
    private javax.swing.JTextPane C34;
    private javax.swing.JTextPane C35;
    private javax.swing.JTextPane C36;
    private javax.swing.JTextPane C37;
    private javax.swing.JTextPane C40;
    private javax.swing.JTextPane C41;
    private javax.swing.JTextPane C42;
    private javax.swing.JTextPane C43;
    private javax.swing.JTextPane C44;
    private javax.swing.JTextPane C45;
    private javax.swing.JTextPane C46;
    private javax.swing.JTextPane C47;
    private javax.swing.JTextPane C50;
    private javax.swing.JTextPane C51;
    private javax.swing.JTextPane C52;
    private javax.swing.JTextPane C53;
    private javax.swing.JTextPane C54;
    private javax.swing.JTextPane C55;
    private javax.swing.JTextPane C56;
    private javax.swing.JTextPane C57;
    private javax.swing.JTextPane C60;
    private javax.swing.JTextPane C61;
    private javax.swing.JTextPane C62;
    private javax.swing.JTextPane C63;
    private javax.swing.JTextPane C64;
    private javax.swing.JTextPane C65;
    private javax.swing.JTextPane C66;
    private javax.swing.JTextPane C67;
    private javax.swing.JTextPane C70;
    private javax.swing.JTextPane C71;
    private javax.swing.JTextPane C72;
    private javax.swing.JTextPane C73;
    private javax.swing.JTextPane C74;
    private javax.swing.JTextPane C75;
    private javax.swing.JTextPane C76;
    private javax.swing.JTextPane C77;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane40;
    private javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JScrollPane jScrollPane42;
    private javax.swing.JScrollPane jScrollPane43;
    private javax.swing.JScrollPane jScrollPane44;
    private javax.swing.JScrollPane jScrollPane45;
    private javax.swing.JScrollPane jScrollPane46;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JScrollPane jScrollPane48;
    private javax.swing.JScrollPane jScrollPane49;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane50;
    private javax.swing.JScrollPane jScrollPane51;
    private javax.swing.JScrollPane jScrollPane52;
    private javax.swing.JScrollPane jScrollPane53;
    private javax.swing.JScrollPane jScrollPane54;
    private javax.swing.JScrollPane jScrollPane55;
    private javax.swing.JScrollPane jScrollPane56;
    private javax.swing.JScrollPane jScrollPane57;
    private javax.swing.JScrollPane jScrollPane58;
    private javax.swing.JScrollPane jScrollPane59;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane60;
    private javax.swing.JScrollPane jScrollPane61;
    private javax.swing.JScrollPane jScrollPane62;
    private javax.swing.JScrollPane jScrollPane63;
    private javax.swing.JScrollPane jScrollPane64;
    private javax.swing.JScrollPane jScrollPane65;
    private javax.swing.JScrollPane jScrollPane66;
    private javax.swing.JScrollPane jScrollPane67;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton loadButton;
    private javax.swing.JTextArea planText;
    private javax.swing.JList truckList;
    // End of variables declaration//GEN-END:variables
}
